import { createCard, text, CARD_WIDTH } from '../svg/components.js';
import { CARD_ACCENTS } from '../constants/index.js';
import { theme } from '../svg/theme.js';
import { formatUtcDateTime, escapeSvg } from '../utils/format.js';

/**
 * Renders a compact "last updated" banner card.
 * Shows when the stats were last auto-generated by GitHub Actions.
 */
export function renderLastUpdated(generatedAt: string): string {
  const W = CARD_WIDTH;
  const H = 68;
  const mid = W / 2;
  const formatted = formatUtcDateTime(generatedAt);

  const content = [
    text({
      x: mid,
      y: theme.titleHeight + 16,
      content: `Auto-generated by GitHub Actions  \u00B7  ${escapeSvg(formatted)}`,
      fontSize: theme.fontSize.sm,
      fill: theme.colors.textMuted,
      textAnchor: 'middle',
    }),
  ].join('');

  return createCard(
    { width: W, height: H, title: 'Last Updated', accentColor: CARD_ACCENTS.lastUpdated },
    content
  );
}
